### ISSUE TITLE
NameError: name 'plt' is not defined

### ISSUE THREAD

**Issue by matthewcuyugan** [marceloprates/prettymaps#43]
Hi. How can I fix this error while generating the script? Thanks.

`Traceback (most recent call last):
  File "C:\Users\cuyug\Desktop\TroPYcal codes\prettymaps.py", line 4, in <module>
    from prettymaps import *
  File "C:\Users\cuyug\Desktop\TroPYcal codes\prettymaps.py", line 17, in <module>
    layers = plot(
NameError: name 'plot' is not defined`

**Comment by mei-se** [comment]
You need to import `plt`, like so

```
from matplotlib import pyplot as plt
```

Here you can find a working example:

https://github.com/marceloprates/prettymaps/blob/main/notebooks/examples.ipynb

**Comment by matthewcuyugan** [comment]
> You need to import `plt`, like so
> 
> ```
> from matplotlib import pyplot as plt
> ```
> 
> Here you can find a working example:
> 
> https://github.com/marceloprates/prettymaps/blob/main/notebooks/examples.ipynb

I'm still having the same issue.

Here's the script:

`import sys; sys.path.append('../')

#import vsketch
from prettymaps import *
import matplotlib.font_manager as fm
from matplotlib import pyplot as plt

# Style parameters
palette = ['#433633', '#FF5E5B']
background_c = '#F2F4CB'
dilate = 100

# Setup figure
fig, ax = plt.subplots(figsize = (10, 10), constrained_layout = True)

# Plot
layers = plot(
    (14.5855,120.9939), radius = 500,
    ax = ax,
    layers = {
        'perimeter': {'circle': False, 'dilate': dilate},
        'streets': {
            'width': {
                'primary': 5,
                'secondary': 4,
                'tertiary': 3,
                'residential': 2,
                'footway': 1,
            },
            'circle': False,
            'dilate': dilate
        },
        'building': {
            'tags': {'building': True},
            'union': False,
            'circle': False,
            'dilate': dilate
        },
        'green': {
            'tags': {
                'landuse': ['grass', 'village_green'],
                'leisure': 'park'
            },
            'circle': False,
            'dilate': dilate
        },
    },
    drawing_kwargs = {
        'background': {'fc': '#F2F4CB', 'ec': '#dadbc1', 'hatch': 'ooo...', 'zorder': -1},
        'perimeter': {'fill': False, 'lw': 0, 'zorder': 0},
        'green': {'fc': '#8BB174', 'ec': '#2F3737', 'hatch_c': '#A7C497', 'hatch': 'ooo...', 'lw': 1, 'zorder': 1},
        'water': {'fc': '#a8e1e6', 'ec': '#2F3737', 'hatch_c': '#9bc3d4', 'hatch': 'ooo...', 'lw': 1, 'zorder': 3},
        'streets': {'fc': '#2F3737', 'ec': '#475657', 'alpha': 1, 'lw': 0, 'zorder': 4},
        'building': {'palette': palette, 'ec': '#2F3737', 'lw': .5, 'zorder': 5},
    },
    osm_credit = {'x': .02, 'y': .01, 'color': '#2F3737'}
)

# Set bounds
xmin, ymin, xmax, ymax = layers['perimeter'].bounds
dx, dy = xmax-xmin, ymax-ymin
ax.set_xlim(xmin-.06*dx, xmax+.06*dx)
ax.set_ylim(ymin-.06*dy, ymax+.06*dy)

# Draw left text
ax.text(
    xmin-.06*dx, ymin+.5*dy,
    'Paco, Manila',
    color = '#2F3737',
    rotation = 90,
    fontproperties = fm.FontProperties(fname = '/assets/Permanent_Marker/PermanentMarker-Regular.ttf', size = 35),
)
# Draw top text
ax.text(
    xmax-.35*dx, ymax+.02*dy,
    "14° 58′ N, 120° 99′ E",
    color = '#2F3737',
    fontproperties = fm.FontProperties(fname = '/assets/Permanent_Marker/PermanentMarker-Regular.ttf', size = 20),
)

plt.savefig('../prints/manila.png')
plt.savefig('../prints/manila.svg')`

Here's the error:

![image](https://user-images.githubusercontent.com/89746755/131546346-f33aec9e-6d68-4197-a0cb-533f4fd4be7b.png)

**Comment by matthewcuyugan** [comment]
Found the solution. Thanks!

`#import vsketch

from prettymaps import plot`

**Comment by Jannomag** [comment]
@matthewcuyugan can you share your whole script? I'm trying for hours now but I just got the same error as you did.
