### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'C:\Users\cuyug\assets\Permanent_Marker\PermanentMarker-Regular.ttf`

### ISSUE THREAD

**Issue by matthewcuyugan** [marceloprates/prettymaps#44]
Can someone help me how to fix these errors? Thanks in advance.

`FileNotFoundError:` [Errno 2] No such file or directory: 'C:\\Users\\cuyug\\assets\\Permanent_Marker\\PermanentMarker-Regular.ttf`

`DeprecationWarning: An exception was ignored while fetching the attribute `__array_interface__` from an object of type 'Polygon'.  With the exception of `AttributeError` NumPy will always raise this exception in the future.  Raise this deprecation warning to see the original exception. (Warning added NumPy 1.21)`

**Comment by hanksims** [comment]
That's a font file. You need to have it, and it needs to exist at the path you've specified. 

You can use any TrueType font, so long as your program can find it on your system.

The "PermanentMarker-Regular.ttf" file, which is used in several of the examples, can be downloaded from here:

https://fonts.google.com/specimen/Permanent+Marker

**Comment by matthewcuyugan** [comment]
> That's a font file. You need to have it, and it needs to exist at the path you've specified.
> 
> You can use any TrueType font, so long as your program can find it on your system.
> 
> The "PermanentMarker-Regular.ttf" file, which is used in several of the examples, can be downloaded from here:
> 
> https://fonts.google.com/specimen/Permanent+Marker

Thank you very much!
