### ISSUE TITLE
trees

### ISSUE THREAD

**Issue by mikedewar** [marceloprates/prettymaps#62]
Hi!

Love the libray! 

Was thinking about using it to make a treasure hunt map for my son and his friends. It's perfect, apart from that I can't quite figure out how to plot individual trees (clues will be hidden in them!). I can see them in open street map, I've figured out the tag I think, I just can't quite figure out how to render them. 

I was wondering - is there something special about rendering this sort of thing? Maybe it's a point, rather than a polygon?

Thanks again!

Mike

**Comment by marceloprates** [comment]
Dear Mike,

I'm pleased to know you're using prettymaps to make such a thoughtful gift for your son. I apologize for the late reply, but have included the feature you're looking for.

Some footprints such as 'tree' or 'tree_row' are not Polygons, but Points or Lines (respectively). So to turn them into polygons you must specify a 'point_size' (for points) or 'line_width' (for lines). These parameters are =1 by default, but you can override them like this:

```
'tree': {'tags': {'natural': ['tree']}, 'point_size': 2},
'tree_row': {'tags': {'natural': ['tree_row']}, 'line_width': 3},
```

I hope you can now make that treasure map :)

**Comment by mikedewar** [comment]
thanks! <3
