### ISSUE TITLE
Rotation

### ISSUE THREAD

**Issue by mawise** [marceloprates/prettymaps#63]
Hi,

I love your project, thanks for sharing it!  Is there any way to rotate the underlying map?  I'm doing a city where the roads are just a few degrees off from alignment with North and I'd love to rotate the image.  Any tips?

Thanks,

Matt

**Comment by marceloprates** [comment]
You can use the "rotation" parameter for that. You can also scale with scale_x and scale_y and translate with x and y: https://prettymaps.readthedocs.io/en/latest/prettymaps.html#module-prettymaps

**Comment by mawise** [comment]
Wow, that was a fast response.  Thank you!  (BTW: the "docs" link on the main github readme rendered as raw HTML for me)

**Comment by marceloprates** [comment]
Thanks, I've fixed it
