### ISSUE TITLE
How to get center point for geometries_from_point()

### ISSUE THREAD

**Issue by TakiGuan** [marceloprates/prettymaps#96]
I check the boundary example and want to try some other cities, but I can't find how to calculate or get it from OpenStreetMap. Maybe someone knows if there is a quick way to get the center point. Thanks in advance.

**Comment by AdrianKriger** [comment]
@TakiGuan ---you'll want to select *'Where is this'* on the OpenStreetMap search

![image](https://user-images.githubusercontent.com/59996720/195989314-328d215b-2198-465d-9e2e-2cfe6d12cbf8.png)
